In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('/workspaces/air-quality-politics/data/raw/resultado_final_con_ica_estaciones.csv', sep=';')

In [5]:
df.head()

,codigo_provincia,nombre_provincia,año,sexo,edad,poblacion,tasa_def_tot_1000hab,muertes_totales,muertes_respiratorias,proporcion_muerte_respiratoria,tasa_muerte_respiratoria_1000hab,VALOR_ICA,CATEGORIA_ICA,CONTAMINANTE,LATITUD_MEDIA,LONGITUD_MEDIA,ALTITUD_MEDIA,TIPO_AREA_MAS_FREC,ZONA_MAS_FREC
0,1,ARABA ALAVA,2013,hombres,0-4,1286,2.12,3,0,0.0,0.000,12.5,Buena,O3,42.848726,-2.745441,456.0,SUBURBANA,RESIDENCIAL/COMERCIAL
1,1,ARABA ALAVA,2013,hombres,15-24,2024,0.35,1,0,0.0,0.000,12.5,Buena,O3,42.848726,-2.745441,456.0,SUBURBANA,RESIDENCIAL/COMERCIAL
2,1,ARABA ALAVA,2013,hombres,25-34,4296,0.82,4,0,0.0,0.000,12.5,Buena,O3,42.848726,-2.745441,456.0,SUBURBANA,RESIDENCIAL/COMERCIAL
3,1,ARABA ALAVA,2013,hombres,35-44,4050,0.82,3,6,2.0,1.481,12.5,Buena,O3,42.848726,-2.745441,456.0,SUBURBANA,RESIDENCIAL/COMERCIAL
4,1,ARABA ALAVA,2013,hombres,45-54,1642,3.19,5,39,7.8,23.752,12.5,Buena,O3,42.848726,-2.745441,456.0,SUBURBANA,RESIDENCIAL/COMERCIAL

In [5]:
df.shape

(9360, 19)

In [7]:
df.describe()

/home/codespace/.local/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,codigo_provincia,año,poblacion,tasa_def_tot_1000hab,muertes_totales,muertes_respiratorias,proporcion_muerte_respiratoria,tasa_muerte_respiratoria_1000hab,VALOR_ICA,LATITUD_MEDIA,LONGITUD_MEDIA,ALTITUD_MEDIA
count,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000,7527.0,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000
mean,26.500000,2017.500000,3302.436645,17.812645,96.251923,33.761432,inf,41.343458,15.180769,39.911668,-3.810808,417.930732
std,15.009133,2.872435,2716.600673,42.533044,281.108760,61.520790,NaN,170.766652,4.237292,3.194209,3.616418,311.873868
min,1.000000,2013.000000,19.000000,0.000000,0.000000,0.000000,0.0,0.000000,7.470000,28.295935,-16.709137,1.000000
25%,13.750000,2015.000000,992.750000,0.290000,1.000000,0.000000,0.0,0.000000,12.217500,38.274032,-5.802549,137.261905
50%,26.500000,2017.500000,2677.000000,1.290000,2.000000,3.000000,1.0,0.909000,15.000000,40.830353,-3.645390,357.555556
75%,39.250000,2020.000000,5111.500000,7.380000,10.000000,43.000000,6.0,23.723500,17.395000,42.138146,-1.807605,682.886364
max,52.000000,2022.000000,14732.000000,208.850000,2187.000000,565.000000,inf,3402.778000,28.160000,43.415440,2.820357,1150.000000

In [13]:
df=pd.read_csv('/workspaces/air-quality-politics/data/raw/resultado_final_todo_con_gobierno_y_edades.csv', sep=';')

In [11]:
df.describe()

/home/codespace/.local/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,codigo_provincia_x,año,poblacion,tasa_def_tot_1000hab,muertes_totales,muertes_respiratorias,proporcion_muerte_respiratoria,tasa_muerte_respiratoria_1000hab,VALOR_ICA,LATITUD_MEDIA,LONGITUD_MEDIA,ALTITUD_MEDIA,codigo_provincia_y,mes,edad_min,edad_max
count,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000,7527.0,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000,9360.000000,9360.0,0.0,0.0
mean,26.500000,2017.500000,3302.436645,17.812645,96.251923,33.761432,inf,41.343458,15.180769,39.911668,-3.810808,417.930732,26.500000,1.0,NaN,NaN
std,15.009133,2.872435,2716.600673,42.533044,281.108760,61.520790,NaN,170.766652,4.237292,3.194209,3.616418,311.873868,15.009133,0.0,NaN,NaN
min,1.000000,2013.000000,19.000000,0.000000,0.000000,0.000000,0.0,0.000000,7.470000,28.295935,-16.709137,1.000000,1.000000,1.0,NaN,NaN
25%,13.750000,2015.000000,992.750000,0.290000,1.000000,0.000000,0.0,0.000000,12.217500,38.274032,-5.802549,137.261905,13.750000,1.0,NaN,NaN
50%,26.500000,2017.500000,2677.000000,1.290000,2.000000,3.000000,1.0,0.909000,15.000000,40.830353,-3.645390,357.555556,26.500000,1.0,NaN,NaN
75%,39.250000,2020.000000,5111.500000,7.380000,10.000000,43.000000,6.0,23.723500,17.395000,42.138146,-1.807605,682.886364,39.250000,1.0,NaN,NaN
max,52.000000,2022.000000,14732.000000,208.850000,2187.000000,565.000000,inf,3402.778000,28.160000,43.415440,2.820357,1150.000000,52.000000,1.0,NaN,NaN